name: API Automation with Allure

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: gh-pages-api
  cancel-in-progress: true

jobs:
  api-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./API-Test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew clean test

      - name: Generate Allure Report
        run: allure generate build/allure-results -o allure-report --clean

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: API-Test/allure-report
          publish_branch: gh-pages
          destination_dir: api  # <-- folder di gh-pages

      - name: Add Allure Report link to Summary
        run: |
          REPORT_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY}/api/"
          echo "### ðŸ§ª API Automation Report" >> $GITHUB_STEP_SUMMARY
          echo "- URL: $REPORT_URL" >> $GITHUB_STEP_SUMMARY
