name: API Automation with Allure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  api-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./API-Test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew clean test

      - name: Generate Allure Report
        run: allure generate build/allure-results -o allure-report --clean

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: API-Test/allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./API-Test/allure-report
          publish_branch: gh-pages-api  # <- terpisah dari Web
          destination_dir: ./  # root folder

      - name: Add Allure Report link to Summary
        run: |
          echo "### ðŸ”¹ API Automation Test Result" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: GitHub Actions" >> $GITHUB_STEP_SUMMARY
          echo "- Report Type: Allure HTML Report" >> $GITHUB_STEP_SUMMARY
          echo "- Report URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_STEP_SUMMARY
      
