name: Web Automation Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: gh-pages-web
  cancel-in-progress: true

jobs:
  automation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2.1.0

      - name: Setup gradlew
        working-directory: ./WEB-Test
        run: chmod +x gradlew

      - name: Run Cucumber Tests
        working-directory: ./WEB-Test
        run: ./gradlew clean test

      - name: Prepare Cucumber Report
        run: |
          mkdir -p WEB-Test/build/cucumber-report
          cp WEB-Test/build/cucumber-report/cucumber.html WEB-Test/build/cucumber-report/index.html

      - name: Upload Cucumber Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: WEB-Test/build/cucumber-report

      - name: Deploy Cucumber Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./WEB-Test/build/cucumber-report
          publish_branch: gh-pages
          destination_dir: web  # <-- report WEB disimpan di folder web di gh-pages

      - name: Add Cucumber Report link to Summary
        run: |
          echo "### ðŸ¥’ Cucumber Automation Test Result" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: GitHub Actions" >> $GITHUB_STEP_SUMMARY
          echo "- Report Type: Cucumber HTML Report" >> $GITHUB_STEP_SUMMARY
          echo "- Report URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/web/" >> $GITHUB_STEP_SUMMARY
